# docker build -t object_detector_service .
# docker system prune

FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# Instalar Python 3.10 y herramientas necesarias
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update

RUN apt-get install -y python3.10 python3.10-distutils python3.10-dev python3.10-venv build-essential wget && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3.10 get-pip.py

RUN apt-get clean

RUN mkdir wd
WORKDIR /wd

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cu118
RUN pip install --no-cache-dir torchvision --index-url https://download.pytorch.org/whl/cu118
RUN pip install --no-cache-dir torchaudio --index-url https://download.pytorch.org/whl/cu118

RUN mkdir src
COPY src/ ./src/

RUN python3 src/cache_model.py

# docker run -e PORT=80 -e MODEL_DEVICE=cuda:0 -p 80:80 -it --gpus all object_detector_service
# docker run object_detector_service sleep infinity
CMD exec gunicorn --workers=1 --threads=1 -b :$PORT src.main:app
#CMD python3 src/main.py